apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # arn 값 수정 필요
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:784849575779:certificate/140ed292-6ce2-4a71-bba3-c35bcf858e6e
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
spec:
  ingressClassName: alb
  rules:
    - host: taehoone.shop
      http: 
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-index-service
              port:
                number: 80
        - path: /login.jsp
          pathType: Prefix
          backend:
            service:
              name: nginx-login-service
              port:
                number: 80
        - path: /signup.jsp
          pathType: Prefix
          backend:
            service:
              name: nginx-signup-service
              port:
                number: 80
        - path: /admin.jsp
          pathType: Prefix
          backend:
            service:
              name: nginx-admin-service
              port:
                number: 80
     
